name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - feat/midia-vistoria
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Enviar pasta public como artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
